# Generated by Django 3.1.4 on 2020-12-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gratters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gratter',
        ),
    ]
