# Generated by Django 3.1.4 on 2020-12-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gratters', '0003_gratter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gratter',
        ),
    ]
