# Generated by Django 3.1.4 on 2020-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratters', '0005_gratter'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratter',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
