# Generated by Django 3.1.4 on 2020-12-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratters', '0006_gratter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratter',
            name='title',
            field=models.CharField(default='Congratulations!', max_length=100),
        ),
    ]
