# Generated by Django 3.1.4 on 2020-12-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratters', '0007_auto_20201219_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratter',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
